services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: calendiary
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-network

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - shared-network
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data:

networks:
  shared-network:
    name: myproject_network