spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
      location: ${FILE_UPLOAD_TEMP}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  task:
    scheduling:
      thread-name-prefix: scheduled-task-pool-
      pool:
        size: 10
security:
  debug:
    true
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration: 86400000 # one day
    refresh-token:
      expiration: 604800000 # 7 days
    auto-login:
      expiration: 2592000000

file:
  post:
    upload:
      location: ${FILE_LOCATION}
      temp: ${FILE_UPLOAD_TEMP}
  diary:
    upload:
      location: ${DIARY_FILE_LOCATION}
      temp: ${DIARY_FILE_UPLOAD_TEMP}

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      example:
        board: DEBUG

token:
  cleanup:
    enabled: true
    retention-days: 7  # 만료된 토큰 보관 기간
    batch-size: 1000   # 한 번에 삭제할 토큰 수

app:
  mail:
    from-name: Calendiary